listen_address : /ip4/0.0.0.0/tcp/0
log_level: info
eth_rpc_url: https://polygon-rpc.com
price_topic: BITCOIN
contract_address: 0xf3787681d966249eb4dec209227460c269c2052a
coin_name: bitcoin
private_key: $NODE_PRIVATE_KEY
feed_interval: 60
fee_per_gas: 65
mappings:
  binance:
    - BTCUSDC
    - BTCUSDT
  coinbase:
    - BTC-USD
    - BTC-USDC
  uniswapv3:
    - 0x99ac8ca7087fa4a2a1fb6357269965a2014abc35
    - 0x9db9e0e53058c89e5b94e29621a205198648425b
  ftx:
    - BTC/USD
    - BTC/USDT
  kucoin:
    - BTC-USDT
    - BTC-USDC
peers:
  - ""