#p2p listen address, ${ip}/tcp/${port}, if port is zero, random port will be used
listen_address : /ip4/0.0.0.0/tcp/0

#log level, info/warn/debug, $RUST_LOG enviroment variable can be used too
log_level: info

#RPC URL of Ethereum chain
eth_rpc_url: https://polygon-rpc.com

#p2p message topic, use sperated topic for each coin price feeding
price_topic: BITCOIN

#smart contract address
contract_address: 0x84e2e15c603fa7649a33106b52bc2081163e588e

#coin name flag which should be same as the one specified in contract
coin_name: bitcoin

#enviroment variables contains wallet key
private_key: $NODE_PRIVATE_KEY

#the interval in seconds between twice pricing feeding
feed_interval: 60

#suggested max fee per gas
fee_per_gas: 65

#trading pairs used of CEX & DEX to aggrate price
mappings:
  binance:
    - BTCUSDC
    - BTCUSDT div USDCUSDT
  coinbase:
    - BTC-USD
    - BTC-USDC
  uniswapv3:
    - 0x99ac8ca7087fa4a2a1fb6357269965a2014abc35 #WBTC-USDC
    - 0xcbcdf9626bc03e24f779434178a73a0b4bad62ed div 0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8 #WBTC-ETH div USDC-ETH
  uniswapv2:
    - 0x004375dff511095cc5a197a54140a24efef3a416 #WBTC-USDC
    - 0xbb2b8038a1640196fbe3e38816f3e67cba72d940 div 0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc #WBTC-ETH div USDC-ETH
  ftx:
    - BTC/USD
    - BTC/USDT mul USDT/USD
  kucoin:
    - BTC-USDT mul USDT-USDC
    - BTC-USDC

#specify some bootstrap nodes, one for each line
peers:
  - ""