#p2p listen address, ${ip}/tcp/${port}, if port is zero, random port will be used
listen_address : /ip4/0.0.0.0/tcp/0

#log level, info/warn/debug, $RUST_LOG enviroment variable can be used too
log_level: info

#RPC URL of Ethereum chain
eth_rpc_url: https://polygon-rpc.com

#p2p message topic, use sperated topic for each coin price feeding
price_topic: BITCOIN

#smart contract address
contract_address: 0x84e2e15c603fa7649a33106b52bc2081163e588e

#coin name flag which should be same as the one specified in contract
coin_name: bitcoin

#enviroment variables contains wallet key
private_key: $NODE_PRIVATE_KEY

#the interval in seconds between twice pricing feeding
feed_interval: 60

#suggested max fee per gas
fee_per_gas: 65

#trading pairs used of CEX & DEX to aggrate price
mappings:
  binance:
    - BTCUSDC
    - BTCUSDT
  coinbase:
    - BTC-USD
    - BTC-USDC
  uniswapv3:
    - 0x99ac8ca7087fa4a2a1fb6357269965a2014abc35
    - 0x9db9e0e53058c89e5b94e29621a205198648425b
  ftx:
    - BTC/USD
    - BTC/USDT
  kucoin:
    - BTC-USDT
    - BTC-USDC

#specify some bootstrap nodes, one for each line
peers:
  - ""